#services:
#    CleanGutter\Services\Marketing\InboudLeadRequestFilter:
#        class: CleanGutter\Http\Event\KernelRequestSubscriber
#        arguments:
#            $logger: '@logger'
#            $securityService: '@security.csrf.token_manager'
#            $templateDataProviders: ['@CleanGutter\Services\TemplateData\HtmlPageDataCompiler']