twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        company_phone: '(478) 216-1140'
        company_email: 'joe@cleangutterco.com'